### ISSUE TITLE
Java 1.6 JRE on Windows 7 - no class name

### ISSUE THREAD

**Issue by Apcio** [mgp/iron-cushion#3]
Hello.
I am not familiar with Java programs.
I tried to run benchmark as is presented in "Running the Benchmark" topic.
I have copied files to different folder:
![test2](https://cloud.githubusercontent.com/assets/11940927/9598119/b1682826-5088-11e5-99f6-c9de4e515a9f.png)

And error, that I can see:
![test1](https://cloud.githubusercontent.com/assets/11940927/9598123/bdf8e206-5088-11e5-9c0a-811f90984214.png)

I have checked on 1.6 and 1.7 Java JRE.

**Comment by d-franklin** [comment]
I know this is old, but the solution on windows is to use the command;

```java -cp "IronCushion-0.1.jar;netty-3.3.1.Final.jar" co.adhoclabs.ironcushion.Benchmark```

Note the quotes and semicolon instead of a colon.

**Comment by Apcio** [comment]
Thank you for the answer, but this problem is resolved long time ago.
Sorry for not closed it before.
